// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVQCDH5aUK6vzmw4XvZWr3B18V1fTrwK8',
    appId: '1:39261851557:web:acda1bfd3fb976a0fc624c',
    messagingSenderId: '39261851557',
    projectId: 'signin-with-e455b',
    authDomain: 'signin-with-e455b.firebaseapp.com',
    storageBucket: 'signin-with-e455b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCywwWj26H7vGUPYwHa9cbmKWiruknSgM',
    appId: '1:39261851557:android:d03b8a58c71c2f40fc624c',
    messagingSenderId: '39261851557',
    projectId: 'signin-with-e455b',
    storageBucket: 'signin-with-e455b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrxFGju_4EZN0987fmQuINIuG2hFhGc24',
    appId: '1:39261851557:ios:69e95ab402a66660fc624c',
    messagingSenderId: '39261851557',
    projectId: 'signin-with-e455b',
    storageBucket: 'signin-with-e455b.appspot.com',
    iosClientId: '39261851557-ka89224v371ghqvbq8n7t0u2aks98gtr.apps.googleusercontent.com',
    iosBundleId: 'com.example.signinWithGoogle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrxFGju_4EZN0987fmQuINIuG2hFhGc24',
    appId: '1:39261851557:ios:69e95ab402a66660fc624c',
    messagingSenderId: '39261851557',
    projectId: 'signin-with-e455b',
    storageBucket: 'signin-with-e455b.appspot.com',
    iosClientId: '39261851557-ka89224v371ghqvbq8n7t0u2aks98gtr.apps.googleusercontent.com',
    iosBundleId: 'com.example.signinWithGoogle',
  );
}
